### ISSUE TITLE
esercizio A - chiamata 2 - significato di "bottino"

### ISSUE THREAD

**Issue by edoven** [Kopjra/laravel-example#1]
Ho capito che ci sono:
1) degli oggetti
2) dei tesori (id, oggetti)
3) dei richiedenti (id, ... , oggetti)

Non ho capito quindi il significato di "bottino" in riferimento a "Valore totale del bottino per tesoro". 
Mi verrebbe da pensare che in realtà sia banalmente una cosa tipo "Valore dei singoli tesori" che restituisca quindi una lista di coppie (id_tesoro, somma_valore_oggetti_tesoro) ma non vorrei essermi perso qualcosa.

**Comment by emanuelecasadio** [comment]
Ciao, una possibile interpretazione è la seguente: "una volta specificato l'id di un tesoro, voglio sapere la somma del valore totale degli oggetti appartenenti a tale tesoro".

Fammi sapere se questa risposta ha chiarito i tuoi dubbi!

**Comment by edoven** [comment]
Ciao,

si, chiarissimo, è proprio come immaginavo. Grazie!
