### ISSUE TITLE
esercizio A - richiedente

### ISSUE THREAD

**Issue by edoven** [Kopjra/laravel-example#2]
Il campo "budget" nel richiedente posso considerarlo legato al richiedente o può variare in base alla richiesta?
Cioè devo considerare questa soluzione:

richiedente(id, nome, budget, data)
richiesta(richiedente, list<oggetto>)

o questa:

richiedente(id, nome, data)
richiesta(richiedente, budget, list<oggetto>)

?

**Comment by emanuelecasadio** [comment]
In questo modello molto semplice la relazione tra richiesta e richiedente è sempre 1:1 (ad un richiedente è associata sempre e solo una specifica richiesta), pertanto puoi gestirlo come preferisci.

**Comment by edoven** [comment]
Ok, perfetto!
